// Generated by tools/generate-kotlin-observation.py. Private ABI v2, pack(8).
package fr.nimby.sdk.internal
import com.sun.jna.Pointer
internal fun Pointer.utf8(offset: Long, size: Int): String {
    val bytes = getByteArray(offset, size)
    val end = bytes.indexOf(0).let { if (it < 0) size else it }
    return bytes.copyOf(end).toString(Charsets.UTF_8)
}
internal class NimbySdkVersion(private val p: Pointer) {
    companion object { const val SIZE = 20 }
    val structSize: Int get() = p.getInt(0L)
    val abiVersion: Int get() = p.getInt(4L)
    val major: Int get() = p.getInt(8L)
    val minor: Int get() = p.getInt(12L)
    val patch: Int get() = p.getInt(16L)
}
internal class NimbyBinaryInfo(private val p: Pointer) {
    companion object { const val SIZE = 88 }
    val structSize: Int get() = p.getInt(0L)
    val recognizedResearchBuild: Int get() = p.getInt(4L)
    val fileSize: Long get() = p.getLong(8L)
    val sha256: String get() = p.utf8(16L, 65)
}
internal class NimbyTrain(private val p: Pointer) {
    companion object { const val SIZE = 304 }
    val id: Long get() = p.getLong(0L)
    val trackId: Long get() = p.getLong(8L)
    val speedMps: Double get() = p.getDouble(16L)
    val trackFraction: Double get() = p.getDouble(24L)
    val direction: Int get() = p.getInt(32L)
    val flags: Int get() = p.getInt(36L)
    val nameUtf8: String get() = p.utf8(40L, 257)
}
internal class NimbyTrainService(private val p: Pointer) {
    companion object { const val SIZE = 400 }
    val trainId: Long get() = p.getLong(0L)
    val flags: Int get() = p.getInt(8L)
    val motionFlags: Int get() = p.getInt(12L)
    val status: Int get() = p.getInt(16L)
    val alert: Int get() = p.getInt(20L)
    val locationTrackId: Long get() = p.getLong(24L)
    val locationStationId: Long get() = p.getLong(32L)
    val lineId: Long get() = p.getLong(40L)
    val stopTrackId: Long get() = p.getLong(48L)
    val stopStationId: Long get() = p.getLong(56L)
    val gameTimeUs: Long get() = p.getLong(64L)
    val arrivalTimeUs: Long get() = p.getLong(72L)
    val departureTimeUs: Long get() = p.getLong(80L)
    val dispatchTimeUs: Long get() = p.getLong(88L)
    val gameEpochSeconds: Long get() = p.getLong(96L)
    val arrivalRemainingSeconds: Double get() = p.getDouble(104L)
    val departureRemainingSeconds: Double get() = p.getDouble(112L)
    val dispatchRemainingSeconds: Double get() = p.getDouble(120L)
    val stopIndex: Int get() = p.getInt(128L)
    val lineKind: Int get() = p.getInt(132L)
    val lineNameUtf8: String get() = p.utf8(136L, 257)
}
internal class NimbyTrainDetails(private val p: Pointer) {
    companion object { const val SIZE = 40 }
    val trainId: Long get() = p.getLong(0L)
    val scheduleId: Long get() = p.getLong(8L)
    val shiftId: Long get() = p.getLong(16L)
    val flags: Int get() = p.getInt(24L)
    val passengerCount: Int get() = p.getInt(28L)
    val orderIndex: Int get() = p.getInt(32L)
    val orderMode: Int get() = p.getInt(36L)
}
internal class NimbyLineStop(private val p: Pointer) {
    companion object { const val SIZE = 40 }
    val lineId: Long get() = p.getLong(0L)
    val trackId: Long get() = p.getLong(8L)
    val stationId: Long get() = p.getLong(16L)
    val index: Int get() = p.getInt(24L)
    val flags: Int get() = p.getInt(28L)
    val arrivalOffsetSeconds: Int get() = p.getInt(32L)
    val departureOffsetSeconds: Int get() = p.getInt(36L)
}
internal class NimbyTrack(private val p: Pointer) {
    companion object { const val SIZE = 24 }
    val id: Long get() = p.getLong(0L)
    val stationId: Long get() = p.getLong(8L)
    val speedLimitMps: Double get() = p.getDouble(16L)
}
internal class NimbyPlatform(private val p: Pointer) {
    companion object { const val SIZE = 288 }
    val trackId: Long get() = p.getLong(0L)
    val stationId: Long get() = p.getLong(8L)
    val flags: Int get() = p.getInt(16L)
    val nameUtf8: String get() = p.utf8(24L, 257)
}
internal class NimbyStation(private val p: Pointer) {
    companion object { const val SIZE = 272 }
    val id: Long get() = p.getLong(0L)
    val nameUtf8: String get() = p.utf8(8L, 257)
}
internal class NimbySignal(private val p: Pointer) {
    companion object { const val SIZE = 32 }
    val id: Long get() = p.getLong(0L)
    val trackId: Long get() = p.getLong(8L)
    val trackFraction: Double get() = p.getDouble(16L)
    val direction: Int get() = p.getInt(24L)
    val kind: Int get() = p.getInt(28L)
}
internal class NimbySignalState(private val p: Pointer) {
    companion object { const val SIZE = 120 }
    val signalId: Long get() = p.getLong(0L)
    val flags: Int get() = p.getInt(8L)
    val aspect: Int get() = p.getInt(12L)
    val textureState: Int get() = p.getInt(16L)
    val exceptionCount: Int get() = p.getInt(20L)
    val systemUtf8: String get() = p.utf8(24L, 32)
    val specificStateUtf8: String get() = p.utf8(56L, 64)
}
internal class NimbySignalTexture(private val p: Pointer) {
    companion object { const val SIZE = 1960 }
    val signalId: Long get() = p.getLong(0L)
    val texturesHash: Long get() = p.getLong(8L)
    val fileHash: Long get() = p.getLong(16L)
    val flags: Int get() = p.getInt(24L)
    val selectedIndex: Int get() = p.getInt(28L)
    val stateCount: Int get() = p.getInt(32L)
    val source: Int get() = p.getInt(36L)
    val texturesIdUtf8: String get() = p.utf8(40L, 128)
    val modIdUtf8: String get() = p.utf8(168L, 256)
    val relativePathUtf8: String get() = p.utf8(424L, 512)
    val filePathUtf8: String get() = p.utf8(936L, 1024)
}
internal class NimbyTrackNode(private val p: Pointer) {
    companion object { const val SIZE = 40 }
    val id: Long get() = p.getLong(0L)
    val linkA: Long get() = p.getLong(8L)
    val linkB: Long get() = p.getLong(16L)
    val x: Double get() = p.getDouble(24L)
    val y: Double get() = p.getDouble(32L)
}
internal class NimbyTrackJunction(private val p: Pointer) {
    companion object { const val SIZE = 32 }
    val branchTrackId: Long get() = p.getLong(0L)
    val mainTrackId: Long get() = p.getLong(8L)
    val mainFraction: Double get() = p.getDouble(16L)
    val mainDirection: Int get() = p.getInt(24L)
    val branchDirection: Int get() = p.getInt(28L)
}
internal class NimbyTrackMetric(private val p: Pointer) {
    companion object { const val SIZE = 16 }
    val trackId: Long get() = p.getLong(0L)
    val lengthM: Double get() = p.getDouble(8L)
}
internal class NimbyTrackUsage(private val p: Pointer) {
    companion object { const val SIZE = 32 }
    val trainId: Long get() = p.getLong(0L)
    val trackId: Long get() = p.getLong(8L)
    val fractionBegin: Double get() = p.getDouble(16L)
    val fractionEnd: Double get() = p.getDouble(24L)
}
internal class NimbySnapshotInfo(private val p: Pointer) {
    companion object { const val SIZE = 112 }
    val structSize: Int get() = p.getInt(0L)
    val abiVersion: Int get() = p.getInt(4L)
    val processId: Int get() = p.getInt(8L)
    val flags: Int get() = p.getInt(12L)
    val capturedUnixMs: Long get() = p.getLong(16L)
    val trainCount: Int get() = p.getInt(24L)
    val trackCount: Int get() = p.getInt(28L)
    val stationCount: Int get() = p.getInt(32L)
    val signalCount: Int get() = p.getInt(36L)
    val gameSha256: String get() = p.utf8(40L, 65)
}
internal class NimbySimulationClock(private val p: Pointer) {
    companion object { const val SIZE = 24 }
    val structSize: Int get() = p.getInt(0L)
    val epochSeconds: Long get() = p.getLong(8L)
    val ticks: Long get() = p.getLong(16L)
}
internal class NimbyGameSession(private val p: Pointer) {
    companion object { const val SIZE = 48 }
    val structSize: Int get() = p.getInt(0L)
    val generation: Long get() = p.getLong(8L)
}
internal class NimbySignalExtensionsState(private val p: Pointer) {
    companion object { const val SIZE = 16 }
    val signalId: Long get() = p.getLong(0L)
    val available: Int get() = p.getInt(8L)
}
internal class NimbySignalExtensionField(private val p: Pointer) {
    companion object { const val SIZE = 544 }
    val signalId: Long get() = p.getLong(0L)
    val scriptId: Long get() = p.getLong(8L)
    val booleanValid: Int get() = p.getInt(16L)
    val booleanValue: Int get() = p.getInt(20L)
    val typeName: String get() = p.utf8(24L, 257)
    val fieldName: String get() = p.utf8(281L, 257)
}
