# Windows runtime, bridges and diagnostics. All paths are SDK-root relative.
# Keep output names stable: the Hub and installed Kotlin kits consume them.
add_library(nimby_build INTERFACE)
target_compile_definitions(nimby_build INTERFACE WIN32_LEAN_AND_MEAN NOMINMAX)
if(MSVC)
    target_compile_options(nimby_build INTERFACE /W4 /permissive- /utf-8)
else()
    target_compile_options(nimby_build INTERFACE -Wall -Wextra -Wpedantic)
endif()
add_library(nimby_minhook STATIC
    third_party/windows/minhook/buffer.c
    third_party/windows/minhook/hook.c
    third_party/windows/minhook/trampoline.c
    third_party/windows/minhook/hde/hde64.c)
target_include_directories(nimby_minhook SYSTEM PUBLIC third_party/windows/minhook)
add_library(nimby_hook_backend STATIC src/platform/windows/hooks/backend.cpp)
target_include_directories(nimby_hook_backend PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(nimby_hook_backend PUBLIC nimby_minhook PRIVATE nimby_build)
add_library(NimbyRailsFranceSDK SHARED
    src/main.cpp
    src/platform/windows/dll_entry.cpp
    src/platform/windows/observation_process.cpp
    src/platform/windows/runtime/lifecycle.cpp
    src/platform/windows/runtime/bootstrap.cpp
    src/runtime/runtime.cpp
    src/runtime/observation.cpp
    src/platform/windows/runtime/clock_bridge_client.cpp
    src/platform/windows/runtime/construction_bridge_client.cpp
    src/platform/windows/runtime/automatic_driving_client.cpp src/platform/windows/runtime/control_client.cpp
    src/runtime/texture_client.cpp
    src/platform/windows/runtime/texture_bridge_client.cpp
    src/platform/windows/runtime/signal_ui_bridge_client.cpp
    src/engine/live_state.cpp
    src/engine/driving.cpp
    src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp
    src/engine/signal_textures.cpp
    src/engine/track_usage.cpp
    src/platform/windows/engine/binary_identity.cpp)
target_compile_definitions(NimbyRailsFranceSDK PRIVATE NIMBY_SDK_BUILD)
target_include_directories(NimbyRailsFranceSDK
    PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>" "$<INSTALL_INTERFACE:include>")
target_link_libraries(NimbyRailsFranceSDK PRIVATE nimby_build bcrypt nimby_hook_backend)
set_target_properties(NimbyRailsFranceSDK PROPERTIES PREFIX "" EXPORT_NAME SDK)
# NimbyRailsFranceSDK::SDK is reserved for the installed package consumed by examples.
if(MINGW)
    # Exceptions stay inside the C ABI. GCC/C++ runtimes are embedded;
    # this MinGW toolchain still requires the shipped libwinpthread-1.dll.
    target_link_options(NimbyRailsFranceSDK PRIVATE -static-libgcc -static-libstdc++)
    target_compile_options(nimby_hook_backend PRIVATE -fno-exceptions -fno-rtti)
    # Keep the runtime matching the selected compiler next to the SDK.
    get_filename_component(NIMBY_COMPILER_BIN "${CMAKE_CXX_COMPILER}" DIRECTORY)
    if(EXISTS "${NIMBY_COMPILER_BIN}/../licenses")
        install(DIRECTORY "${NIMBY_COMPILER_BIN}/../licenses/" DESTINATION share/licenses/MinGW)
    endif()
    foreach(runtime libgcc_s_seh-1.dll libstdc++-6.dll libwinpthread-1.dll)
        if(EXISTS "${NIMBY_COMPILER_BIN}/${runtime}")
            add_custom_command(TARGET NimbyRailsFranceSDK POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${NIMBY_COMPILER_BIN}/${runtime}" "$<TARGET_FILE_DIR:NimbyRailsFranceSDK>")
            install(FILES "${NIMBY_COMPILER_BIN}/${runtime}" DESTINATION bin)
        endif()
    endforeach()
endif()
add_library(nimby_loader_core STATIC src/platform/windows/loader/loader.cpp src/platform/windows/engine/binary_identity.cpp)
target_include_directories(nimby_loader_core PUBLIC include)
target_compile_definitions(nimby_loader_core PUBLIC _WIN32_WINNT=0x0A00)
target_link_libraries(nimby_loader_core PUBLIC nimby_build bcrypt)
target_link_libraries(NimbyRailsFranceSDK PRIVATE nimby_loader_core)
add_executable(NimbyRailsFranceLoader src/platform/windows/loader/main.cpp)
target_link_libraries(NimbyRailsFranceLoader PRIVATE nimby_loader_core)
if(MINGW)
    target_link_options(NimbyRailsFranceLoader PRIVATE -municode)
endif()
add_dependencies(NimbyRailsFranceLoader NimbyRailsFranceSDK)
add_library(NimbyRailsFranceClockBridge SHARED src/platform/windows/runtime/clock_bridge.cpp src/platform/windows/engine/binary_identity.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp src/engine/live_state.cpp)
if(MINGW)
    add_library(NimbyRailsFranceTextureBridge SHARED src/platform/windows/runtime/texture_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
    target_include_directories(NimbyRailsFranceTextureBridge PRIVATE include)
    target_link_libraries(NimbyRailsFranceTextureBridge PRIVATE nimby_build nimby_minhook bcrypt)
    target_link_options(NimbyRailsFranceTextureBridge PRIVATE -static-libgcc -static-libstdc++)
    set_target_properties(NimbyRailsFranceTextureBridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyRailsFranceTextureBridge-experimental-v4")
    add_dependencies(NimbyRailsFranceSDK NimbyRailsFranceTextureBridge)
    install(TARGETS NimbyRailsFranceTextureBridge RUNTIME DESTINATION bin)
endif()
target_include_directories(NimbyRailsFranceClockBridge PRIVATE include)
target_link_libraries(NimbyRailsFranceClockBridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(NimbyRailsFranceClockBridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyRailsFranceClockBridge-0.7.1")
add_dependencies(NimbyRailsFranceSDK NimbyRailsFranceClockBridge)
add_library(nimby_mod_metadata_bridge SHARED src/platform/windows/runtime/mod_metadata_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
target_include_directories(nimby_mod_metadata_bridge PRIVATE include)
target_link_libraries(nimby_mod_metadata_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_mod_metadata_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyModMetadataBridge-v1")
if(MINGW)
    target_link_options(nimby_mod_metadata_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
add_dependencies(NimbyRailsFranceSDK nimby_mod_metadata_bridge)
add_executable(nimby_clock_bridge_probe tools/windows/clock_bridge_probe.cpp)
target_link_libraries(nimby_clock_bridge_probe PRIVATE nimby_loader_core)
add_library(nimby_native_driving_probe_bridge SHARED tools/windows/native-driving-probe-bridge.cpp src/platform/windows/engine/binary_identity.cpp)
add_library(nimby_driving_bridge SHARED src/platform/windows/runtime/driving_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
add_library(nimby_automatic_driving_bridge SHARED src/platform/windows/runtime/automatic_driving_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
add_executable(nimby_automatic_driving_status tools/windows/automatic-driving-status.cpp)
add_executable(nimby_signal_settings_profile tools/windows/signal-settings-profile.cpp)
target_include_directories(nimby_signal_settings_profile PRIVATE include)
target_link_libraries(nimby_signal_settings_profile PRIVATE nimby_build)
target_include_directories(nimby_automatic_driving_status PRIVATE include)
target_link_libraries(nimby_automatic_driving_status PRIVATE nimby_build)
target_include_directories(nimby_automatic_driving_bridge PRIVATE include)
target_link_libraries(nimby_automatic_driving_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_automatic_driving_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyAutomaticDrivingBridge-v1")
add_dependencies(NimbyRailsFranceSDK nimby_automatic_driving_bridge)
install(TARGETS nimby_automatic_driving_bridge RUNTIME DESTINATION bin)
if(MINGW)
    target_link_options(nimby_automatic_driving_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
target_include_directories(nimby_driving_bridge PRIVATE include)
target_link_libraries(nimby_driving_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_driving_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyDrivingBridge-experimental-v1")
add_executable(nimby_driving_command_probe tools/windows/driving-command-probe.cpp)
target_link_libraries(nimby_driving_command_probe PRIVATE nimby_loader_core)
if(MINGW)
    target_link_options(nimby_driving_command_probe PRIVATE -municode)
    target_link_options(nimby_driving_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
target_include_directories(nimby_native_driving_probe_bridge PRIVATE include)
target_link_libraries(nimby_native_driving_probe_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_native_driving_probe_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyNativeDrivingProbe-v2")
add_executable(nimby_native_driving_probe tools/windows/native-driving-probe.cpp)
target_link_libraries(nimby_native_driving_probe PRIVATE nimby_loader_core)
if(MINGW)
    target_link_options(nimby_native_driving_probe PRIVATE -municode)
    target_link_options(nimby_native_driving_probe_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
if(MINGW)
    target_link_options(nimby_clock_bridge_probe PRIVATE -municode)
    target_link_options(NimbyRailsFranceClockBridge PRIVATE -static-libgcc -static-libstdc++)
endif()
add_library(NimbyRailsProxy SHARED src/platform/windows/proxy/main.cpp src/platform/windows/proxy/SDL3.def src/platform/windows/engine/binary_identity.cpp src/loader/mods.cpp src/platform/windows/mods.cpp)
target_include_directories(NimbyRailsProxy PRIVATE include)
target_link_libraries(NimbyRailsProxy PRIVATE nimby_build bcrypt)
set_target_properties(NimbyRailsProxy PROPERTIES PREFIX "" OUTPUT_NAME "SDL3"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/drop-in")
if(MINGW)
    target_compile_options(NimbyRailsProxy PRIVATE -fno-exceptions -fno-rtti)
    target_link_options(NimbyRailsProxy PRIVATE -static-libgcc -static-libstdc++)
endif()
add_dependencies(NimbyRailsProxy NimbyRailsFranceSDK)
add_custom_target(nimby_dropin_runtime ALL
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
    "$<TARGET_FILE:NimbyRailsFranceSDK>" "$<TARGET_FILE_DIR:NimbyRailsProxy>")
add_dependencies(nimby_dropin_runtime NimbyRailsProxy NimbyRailsFranceSDK)
add_custom_command(TARGET nimby_dropin_runtime POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
    "$<TARGET_FILE:nimby_automatic_driving_bridge>" "$<TARGET_FILE_DIR:NimbyRailsProxy>")
if(MINGW)
    add_custom_command(TARGET nimby_dropin_runtime POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "${NIMBY_COMPILER_BIN}/libwinpthread-1.dll" "$<TARGET_FILE_DIR:NimbyRailsProxy>")
    add_custom_command(TARGET nimby_dropin_runtime POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
        "$<TARGET_FILE:NimbyRailsFranceTextureBridge>" "$<TARGET_FILE_DIR:NimbyRailsProxy>")
endif()
foreach(tool signalling-study signalling-track-study signalling-driving-live sdk-control)
    string(REPLACE "-" "_" target_name "nimby_${tool}")
    set(tool_source "tools/${tool}.cpp")
    add_executable(${target_name} "${tool_source}")
    target_include_directories(${target_name} PRIVATE include)
    target_link_libraries(${target_name} PRIVATE NimbyRailsFranceSDK nimby_build)
    if(MINGW)
        target_link_options(${target_name} PRIVATE -static-libgcc -static-libstdc++)
    endif()
    install(TARGETS ${target_name} RUNTIME DESTINATION bin)
endforeach()
add_executable(nimby_signal_extension_probe tools/windows/signal_extension_probe.cpp src/platform/windows/engine/binary_identity.cpp src/engine/live_state.cpp)
add_executable(nimby_versioning_probe tools/windows/versioning_probe.cpp src/platform/windows/engine/binary_identity.cpp src/engine/live_state.cpp)
add_executable(nimby_signal_settings_probe tools/signal-settings-probe.cpp)
add_executable(nimby_train_service_probe tools/windows/train-service-probe.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp src/engine/track_usage.cpp src/platform/windows/engine/binary_identity.cpp src/engine/live_state.cpp)
target_include_directories(nimby_train_service_probe PRIVATE include)
target_link_libraries(nimby_train_service_probe PRIVATE nimby_build bcrypt)
add_executable(nimby_signal_membership_probe tools/windows/signal-membership-probe.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp src/platform/windows/engine/binary_identity.cpp src/engine/live_state.cpp)
target_include_directories(nimby_signal_membership_probe PRIVATE include)
target_link_libraries(nimby_signal_membership_probe PRIVATE nimby_build bcrypt)
target_link_libraries(nimby_signal_settings_probe PRIVATE NimbyRailsFranceSDK nimby_build)
add_library(nimby_signal_ui_probe_bridge SHARED tools/windows/signal_ui_probe_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
add_library(nimby_signal_ui_bridge SHARED src/platform/windows/runtime/signal_ui_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
target_include_directories(nimby_signal_ui_bridge PRIVATE include)
target_link_libraries(nimby_signal_ui_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_signal_ui_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbySignalUiBridge-experimental-v1")
add_dependencies(NimbyRailsFranceSDK nimby_signal_ui_bridge)
install(TARGETS nimby_signal_ui_bridge RUNTIME DESTINATION bin)
add_custom_command(TARGET nimby_dropin_runtime POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
    "$<TARGET_FILE:nimby_signal_ui_bridge>" "$<TARGET_FILE_DIR:NimbyRailsProxy>")
if(MINGW)
    target_link_options(nimby_signal_ui_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
target_include_directories(nimby_signal_ui_probe_bridge PRIVATE include)
target_link_libraries(nimby_signal_ui_probe_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_signal_ui_probe_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbySignalUiProbe-v1")
add_executable(nimby_signal_ui_probe tools/windows/signal_ui_probe.cpp)
target_link_libraries(nimby_signal_ui_probe PRIVATE nimby_loader_core)
add_library(nimby_construction_probe_bridge SHARED tools/windows/construction-probe-bridge.cpp src/platform/windows/engine/binary_identity.cpp)
add_library(nimby_construction_bridge SHARED EXCLUDE_FROM_ALL
    src/platform/windows/runtime/construction_bridge.cpp src/platform/windows/engine/binary_identity.cpp)
target_include_directories(nimby_construction_bridge PRIVATE include)
target_link_libraries(nimby_construction_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_construction_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyConstructionBridge-experimental-v1")
# Qualification artifact only: deliberately absent from install/drop-in targets.
option(NIMBY_DEVELOPMENT_CONSTRUCTION "Include the single-player construction qualification bridge in local developer kits" OFF)
if(NIMBY_DEVELOPMENT_CONSTRUCTION)
    add_dependencies(NimbyRailsFranceSDK nimby_construction_bridge)
    install(TARGETS nimby_construction_bridge RUNTIME DESTINATION bin)
endif()
if(MINGW)
    target_link_options(nimby_construction_bridge PRIVATE -static-libgcc -static-libstdc++)
endif()
target_include_directories(nimby_construction_probe_bridge PRIVATE include)
target_link_libraries(nimby_construction_probe_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_construction_probe_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyConstructionProbe-v1")
add_executable(nimby_construction_probe tools/windows/construction-probe.cpp)
target_link_libraries(nimby_construction_probe PRIVATE nimby_loader_core)
add_library(nimby_construction_batch_probe_bridge SHARED tools/windows/construction-batch-probe-bridge.cpp src/platform/windows/engine/binary_identity.cpp)
target_include_directories(nimby_construction_batch_probe_bridge PRIVATE include)
target_link_libraries(nimby_construction_batch_probe_bridge PRIVATE nimby_build nimby_minhook bcrypt)
set_target_properties(nimby_construction_batch_probe_bridge PROPERTIES PREFIX "" OUTPUT_NAME "NimbyConstructionBatchProbe-v1")
add_executable(nimby_construction_batch_probe tools/windows/construction-batch-probe.cpp)
target_link_libraries(nimby_construction_batch_probe PRIVATE nimby_loader_core)
if(MINGW)
    target_link_options(nimby_construction_batch_probe_bridge PRIVATE -static-libgcc -static-libstdc++)
    target_link_options(nimby_construction_batch_probe PRIVATE -municode)
    target_link_options(nimby_construction_probe_bridge PRIVATE -static-libgcc -static-libstdc++)
    target_link_options(nimby_construction_probe PRIVATE -municode)
endif()
if(MINGW)
    target_link_options(nimby_signal_ui_probe_bridge PRIVATE -static-libgcc -static-libstdc++)
    target_link_options(nimby_signal_ui_probe PRIVATE -municode)
endif()
target_include_directories(nimby_versioning_probe PRIVATE include)
target_link_libraries(nimby_versioning_probe PRIVATE nimby_build bcrypt)
target_include_directories(nimby_signal_extension_probe PRIVATE include)
target_link_libraries(nimby_signal_extension_probe PRIVATE nimby_build bcrypt)
add_executable(NimbyTrainMonitor WIN32 src/platform/windows/train_monitor.cpp src/platform/windows/engine/binary_identity.cpp src/engine/live_state.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp)
target_include_directories(NimbyTrainMonitor PRIVATE include)
target_compile_definitions(NimbyTrainMonitor PRIVATE UNICODE _UNICODE)
target_link_libraries(NimbyTrainMonitor PRIVATE nimby_build bcrypt comctl32 gdi32)
if(MINGW)
    foreach(runtime libgcc_s_seh-1.dll libstdc++-6.dll libwinpthread-1.dll)
        if(EXISTS "${NIMBY_COMPILER_BIN}/${runtime}")
            add_custom_command(TARGET NimbyTrainMonitor POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "${NIMBY_COMPILER_BIN}/${runtime}" "$<TARGET_FILE_DIR:NimbyTrainMonitor>")
        endif()
    endforeach()
endif()
