# Windows execution tests plus common contracts exercised on Windows.
# All assertions must execute in Release too; NDEBUG must never disable a test.
if(BUILD_TESTING)
    add_library(nimby_construction_transport_fixture SHARED tests/windows/construction_transport_fixture.cpp)
    target_include_directories(nimby_construction_transport_fixture PRIVATE include)
    target_link_libraries(nimby_construction_transport_fixture PRIVATE nimby_build)
    set_target_properties(nimby_construction_transport_fixture PROPERTIES PREFIX "" OUTPUT_NAME "NimbyConstructionBridge-experimental-v1"
        RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/construction-transport-fixture"
        ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/construction-transport-fixture")
    add_executable(nimby_construction_transport_tests tests/windows/construction_transport.cpp src/platform/windows/runtime/construction_bridge_client.cpp)
    target_include_directories(nimby_construction_transport_tests PRIVATE include)
    target_link_libraries(nimby_construction_transport_tests PRIVATE nimby_build nimby_loader_core)
    set_target_properties(nimby_construction_transport_tests PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/construction-transport-fixture")
    add_dependencies(nimby_construction_transport_tests nimby_construction_transport_fixture)
    add_test(NAME construction_in_process_transport COMMAND nimby_construction_transport_tests)
    set_tests_properties(construction_in_process_transport PROPERTIES TIMEOUT 20)
    add_executable(nimby_diagnostics_tests tests/windows/diagnostics.cpp)
    target_link_libraries(nimby_diagnostics_tests PRIVATE nimby_build)
    target_include_directories(nimby_diagnostics_tests PRIVATE include)
    add_test(NAME persistent_diagnostics COMMAND nimby_diagnostics_tests)
    add_executable(nimby_control_pipe_tests tests/windows/control_pipe.cpp)
    target_link_libraries(nimby_control_pipe_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME mod_control_windows_pipe COMMAND nimby_control_pipe_tests)
    set_tests_properties(mod_control_windows_pipe PROPERTIES TIMEOUT 10)
    add_test(NAME sdk_control_help COMMAND nimby_sdk_control help)
    add_test(NAME sdk_control_invalid COMMAND nimby_sdk_control train 0 bad)
    set_tests_properties(sdk_control_invalid PROPERTIES WILL_FAIL TRUE)
    add_test(NAME signalling_study_help COMMAND nimby_signalling_study help)
    add_test(NAME signalling_study_invalid_id COMMAND nimby_signalling_study watch -1 2 100)
    add_test(NAME signalling_study_unbounded_watch COMMAND nimby_signalling_study watch 1 1001 100)
    set_tests_properties(signalling_study_invalid_id signalling_study_unbounded_watch PROPERTIES WILL_FAIL TRUE)
    add_executable(nimby_automatic_driving_tests tests/automatic_driving.cpp)
    target_include_directories(nimby_automatic_driving_tests PRIVATE include)
    target_link_libraries(nimby_automatic_driving_tests PRIVATE nimby_build)
    if(MINGW)
        target_compile_options(nimby_automatic_driving_tests PRIVATE -UNDEBUG)
    endif()
    add_test(NAME automatic_driving_rules COMMAND nimby_automatic_driving_tests)
    add_executable(nimby_automatic_driving_native_tests tests/windows/automatic_driving_native.cpp src/platform/windows/engine/binary_identity.cpp)
    target_include_directories(nimby_automatic_driving_native_tests PRIVATE include)
    target_link_libraries(nimby_automatic_driving_native_tests PRIVATE nimby_build nimby_minhook bcrypt)
    add_test(NAME automatic_driving_permission_bridge COMMAND nimby_automatic_driving_native_tests)
    set_tests_properties(automatic_driving_permission_bridge PROPERTIES TIMEOUT 10)
    add_executable(nimby_observation_loop_tests tests/observation_loop.cpp)
    target_link_libraries(nimby_observation_loop_tests PRIVATE nimby_build)
    target_include_directories(nimby_observation_loop_tests PRIVATE include)
    add_test(NAME mod_observation_loop COMMAND nimby_observation_loop_tests)
    set_tests_properties(mod_observation_loop PROPERTIES TIMEOUT 10)
    add_executable(nimby_block_topology_tests tests/block_topology.cpp)
    target_include_directories(nimby_block_topology_tests PRIVATE include)
    target_link_libraries(nimby_block_topology_tests PRIVATE nimby_build)
    add_test(NAME block_topology COMMAND nimby_block_topology_tests)
    add_executable(nimby_signalling_runtime_tests tests/signalling_runtime.cpp)
    target_link_libraries(nimby_signalling_runtime_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME generic_signalling_runtime COMMAND nimby_signalling_runtime_tests)
    add_executable(nimby_signalling_control_tests tests/signalling_control.cpp)
    target_link_libraries(nimby_signalling_control_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME signalling_control_overlays COMMAND nimby_signalling_control_tests)
    add_executable(nimby_blocks_tests tests/blocks.cpp)
    target_include_directories(nimby_blocks_tests PRIVATE include)
    target_link_libraries(nimby_blocks_tests PRIVATE nimby_build)
    add_test(NAME blocks_and_signal_network COMMAND nimby_blocks_tests)
    add_executable(nimby_signal_extensions_tests tests/signal_extensions.cpp)
    target_include_directories(nimby_signal_extensions_tests PRIVATE include)
    target_link_libraries(nimby_signal_extensions_tests PRIVATE nimby_build)
    add_test(NAME signal_extension_read_guards COMMAND nimby_signal_extensions_tests)
    add_executable(nimby_signal_settings_store_tests tests/signal_settings_store.cpp)
    target_include_directories(nimby_signal_settings_store_tests PRIVATE include)
    target_link_libraries(nimby_signal_settings_store_tests PRIVATE nimby_build)
    add_test(NAME cpp_signal_settings_store COMMAND nimby_signal_settings_store_tests)
    add_executable(nimby_signal_settings_file_tests tests/signal_settings_file.cpp)
    target_include_directories(nimby_signal_settings_file_tests PRIVATE include)
    target_link_libraries(nimby_signal_settings_file_tests PRIVATE nimby_build)
    add_test(NAME cpp_signal_settings_file COMMAND nimby_signal_settings_file_tests)
    add_executable(nimby_signal_ui_tests tests/signal_ui.cpp)
    add_executable(nimby_signal_ui_endpoint_tests tests/signal_ui_endpoint.cpp)
    target_include_directories(nimby_signal_ui_endpoint_tests PRIVATE include)
    target_link_libraries(nimby_signal_ui_endpoint_tests PRIVATE nimby_build)
    add_test(NAME signal_ui_c_abi_model COMMAND nimby_signal_ui_endpoint_tests)
    add_executable(nimby_signal_ui_dll_tests tests/windows/signal_ui_dll.c)
    target_include_directories(nimby_signal_ui_dll_tests PRIVATE include)
    target_link_libraries(nimby_signal_ui_dll_tests PRIVATE nimby_build)
    add_dependencies(nimby_signal_ui_dll_tests nimby_signal_ui_bridge)
    add_test(NAME signal_ui_dll_c_exports COMMAND nimby_signal_ui_dll_tests $<TARGET_FILE:nimby_signal_ui_bridge>)
    add_executable(nimby_signal_settings_client_tests tests/windows/signal_settings_client.cpp)
    add_executable(nimby_signal_settings_catalog_tests tests/signal_settings_catalog.cpp)
    add_executable(nimby_observation_epoch_tests tests/observation_epoch.cpp)
    target_include_directories(nimby_observation_epoch_tests PRIVATE include)
    target_link_libraries(nimby_observation_epoch_tests PRIVATE nimby_build)
    add_test(NAME game_observation_epoch COMMAND nimby_observation_epoch_tests)
    target_include_directories(nimby_signal_settings_catalog_tests PRIVATE include)
    target_link_libraries(nimby_signal_settings_catalog_tests PRIVATE nimby_build)
    add_test(NAME signal_settings_catalog COMMAND nimby_signal_settings_catalog_tests)
    target_include_directories(nimby_signal_settings_client_tests PRIVATE include)
    target_link_libraries(nimby_signal_settings_client_tests PRIVATE nimby_build)
    add_dependencies(nimby_signal_settings_client_tests nimby_signal_ui_bridge)
    add_test(NAME signal_settings_client COMMAND nimby_signal_settings_client_tests $<TARGET_FILE:nimby_signal_ui_bridge>)
    target_include_directories(nimby_signal_ui_tests PRIVATE include)
    target_link_libraries(nimby_signal_ui_tests PRIVATE nimby_build)
    add_test(NAME native_signal_ui_binding COMMAND nimby_signal_ui_tests)
    add_executable(nimby_signal_ui_scroll_tests tests/windows/signal_ui_scroll.cpp)
    target_include_directories(nimby_signal_ui_scroll_tests PRIVATE include)
    target_link_libraries(nimby_signal_ui_scroll_tests PRIVATE nimby_build)
    add_test(NAME native_signal_ui_scroll COMMAND nimby_signal_ui_scroll_tests)
    add_executable(nimby_signal_preview_tests tests/windows/signal_preview.cpp)
    target_include_directories(nimby_signal_preview_tests PRIVATE include)
    target_link_libraries(nimby_signal_preview_tests PRIVATE nimby_build)
    add_test(NAME native_signal_preview COMMAND nimby_signal_preview_tests)
    add_executable(nimby_signal_ui_native_text_tests tests/windows/signal_ui_native_text.cpp src/platform/windows/engine/binary_identity.cpp)
    target_include_directories(nimby_signal_ui_native_text_tests PRIVATE include)
    target_link_libraries(nimby_signal_ui_native_text_tests PRIVATE nimby_build bcrypt)
    add_test(NAME native_signal_ui_text COMMAND nimby_signal_ui_native_text_tests)
    # Optional binary-backed regression. CI without the proprietary game skips
    # this test; local runs opt in with NIMBY_TEST_GAME_EXE. Never starts the game.
    set_tests_properties(native_signal_ui_text PROPERTIES SKIP_RETURN_CODE 77 TIMEOUT 15)
    add_executable(nimby_versioning_tests tests/versioning.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_versioning_tests PRIVATE include)
    target_link_libraries(nimby_versioning_tests PRIVATE nimby_build)
    add_test(NAME versioning_read_guards COMMAND nimby_versioning_tests)
    add_executable(nimby_driving_tests tests/driving.cpp src/engine/driving.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_driving_tests PRIVATE include)
    target_link_libraries(nimby_driving_tests PRIVATE nimby_build)
    add_test(NAME targeted_driving_guards COMMAND nimby_driving_tests)
    add_executable(nimby_driving_api_tests tests/driving_api.cpp)
    target_link_libraries(nimby_driving_api_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME targeted_driving_api COMMAND nimby_driving_api_tests)
    add_executable(nimby_mod_entry_tests tests/windows/mod_entry.cpp src/mod/entry.cpp)
    target_link_libraries(nimby_mod_entry_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME mod_entry_adapter COMMAND nimby_mod_entry_tests)
    add_executable(nimby_texture_command_tests tests/texture_commands.cpp)
    target_link_libraries(nimby_texture_command_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME texture_command_arguments COMMAND nimby_texture_command_tests)
    enable_testing()
    add_executable(nimby_native_observation_tests tests/native_observation.cpp)
    target_include_directories(nimby_native_observation_tests PRIVATE include)
    target_compile_definitions(nimby_native_observation_tests PRIVATE NIMBY_SDK_BUILD)
    target_link_libraries(nimby_native_observation_tests PRIVATE nimby_build)
    add_test(NAME native_observation_helpers COMMAND nimby_native_observation_tests)
    add_executable(nimby_signal_topology_tests tests/signal_topology.cpp)
    target_include_directories(nimby_signal_topology_tests PRIVATE include)
    target_link_libraries(nimby_signal_topology_tests PRIVATE nimby_build)
    add_test(NAME signal_topology COMMAND nimby_signal_topology_tests)
    set_tests_properties(native_observation_helpers PROPERTIES TIMEOUT 20)
    add_executable(nimby_signal_texture_tests tests/signal_textures.cpp src/engine/signal_textures.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_signal_texture_tests PRIVATE include)
    target_link_libraries(nimby_signal_texture_tests PRIVATE nimby_build)
    add_test(NAME signal_texture_catalog COMMAND nimby_signal_texture_tests)
    add_executable(nimby_signal_state_tests tests/signal_states.cpp src/platform/windows/observation_process.cpp
        src/engine/live_state.cpp src/engine/driving.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp src/engine/track_usage.cpp src/engine/signal_textures.cpp src/platform/windows/runtime/clock_bridge_client.cpp)
    target_sources(nimby_signal_state_tests PRIVATE src/platform/windows/runtime/construction_bridge_client.cpp)
    target_include_directories(nimby_signal_state_tests PRIVATE include)
    target_compile_definitions(nimby_signal_state_tests PRIVATE NIMBY_SDK_BUILD)
    target_link_libraries(nimby_signal_state_tests PRIVATE nimby_build nimby_loader_core bcrypt)
    add_test(NAME signal_state_contract COMMAND nimby_signal_state_tests)
    add_executable(nimby_track_usage_tests tests/track_usage.cpp src/engine/track_usage.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_track_usage_tests PRIVATE include)
    target_link_libraries(nimby_track_usage_tests PRIVATE nimby_build)
    add_test(NAME track_usage_guards COMMAND nimby_track_usage_tests)
    add_executable(nimby_observation_tests tests/observation.cpp)
    target_link_libraries(nimby_observation_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME internal_observation_abi COMMAND nimby_observation_tests)
    add_executable(nimby_internal_c_test tests/internal_bridge.c)
    target_compile_features(nimby_internal_c_test PRIVATE c_std_11)
    target_link_libraries(nimby_internal_c_test PRIVATE NimbyRailsFranceSDK)
    add_test(NAME internal_c_bridge COMMAND nimby_internal_c_test)
    add_executable(nimby_network_tests tests/network.cpp src/engine/network.cpp src/engine/trains.cpp src/engine/signal_texture_states.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_network_tests PRIVATE include)
    target_link_libraries(nimby_network_tests PRIVATE nimby_build)
    add_test(NAME network_read_guards COMMAND nimby_network_tests)
    add_executable(nimby_live_state_tests tests/live_state.cpp src/engine/live_state.cpp)
    target_include_directories(nimby_live_state_tests PRIVATE include)
    target_link_libraries(nimby_live_state_tests PRIVATE nimby_build)
    add_test(NAME live_state_resolution COMMAND nimby_live_state_tests)
    add_executable(nimby_native_string_tests tests/native_string.cpp)
    target_include_directories(nimby_native_string_tests PRIVATE include)
    target_link_libraries(nimby_native_string_tests PRIVATE nimby_build)
    add_test(NAME native_string_layouts COMMAND nimby_native_string_tests)
    add_executable(nimby_simulation_clock_tests tests/simulation_clock.cpp)
    target_include_directories(nimby_simulation_clock_tests PRIVATE include)
    target_link_libraries(nimby_simulation_clock_tests PRIVATE nimby_build)
    add_test(NAME simulation_clock_contract COMMAND nimby_simulation_clock_tests)
    add_test(NAME train_probe_guards COMMAND NimbyTrainMonitor --self-test)
    add_executable(nimby_sdk_host tests/windows/host.cpp)
    target_include_directories(nimby_sdk_host PRIVATE include)
    target_link_libraries(nimby_sdk_host PRIVATE nimby_build)
    add_dependencies(nimby_sdk_host NimbyRailsFranceSDK)
    add_test(NAME dll_lifecycle COMMAND nimby_sdk_host "$<TARGET_FILE:NimbyRailsFranceSDK>")
    add_executable(nimby_component_tests tests/windows/components.cpp src/platform/windows/engine/binary_identity.cpp)
    target_include_directories(nimby_component_tests PRIVATE include)
    target_link_libraries(nimby_component_tests PRIVATE nimby_build bcrypt)
    add_test(NAME identity_and_policy COMMAND nimby_component_tests)
    add_executable(nimby_minhook_tests tests/windows/minhook.cpp tests/hook_target.cpp)
    target_link_libraries(nimby_minhook_tests PRIVATE nimby_hook_backend nimby_build)
    add_dependencies(nimby_minhook_tests NimbyRailsFranceSDK)
    add_test(NAME minhook_observation COMMAND nimby_minhook_tests)
    add_executable(nimby_loader_target tests/windows/loader_target.cpp)
    target_include_directories(nimby_loader_target PRIVATE include)
    target_link_libraries(nimby_loader_target PRIVATE nimby_build nimby_minhook)
    add_executable(nimby_loader_tests tests/windows/loader.cpp)
    target_link_libraries(nimby_loader_tests PRIVATE nimby_loader_core)
    if(MINGW)
        target_link_options(nimby_loader_target PRIVATE -municode)
        target_link_options(nimby_loader_tests PRIVATE -municode)
    endif()
    add_dependencies(nimby_loader_tests NimbyRailsFranceSDK nimby_loader_target)
    add_test(NAME loader_restart COMMAND nimby_loader_tests "$<TARGET_FILE:nimby_loader_target>" "$<TARGET_FILE:NimbyRailsFranceSDK>")
    set_tests_properties(loader_restart PROPERTIES TIMEOUT 60)
    add_executable(nimby_proxy_tests tests/windows/proxy.cpp)
    target_link_libraries(nimby_proxy_tests PRIVATE nimby_build)
    if(MINGW)
        target_link_options(nimby_proxy_tests PRIVATE -municode)
    endif()
    add_dependencies(nimby_proxy_tests NimbyRailsProxy)
    # Set this to the unmodified SDL shipped with the game for integration tests.
    set(NIMBY_SDL_ORIGINAL "" CACHE FILEPATH "Original SDL3.dll for optional proxy integration tests")
    if(NIMBY_SDL_ORIGINAL AND EXISTS "${NIMBY_SDL_ORIGINAL}")
        add_custom_command(TARGET NimbyRailsProxy POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_BINARY_DIR}/proxy-test"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "${NIMBY_SDL_ORIGINAL}" "${CMAKE_BINARY_DIR}/proxy-test/NimbyRailsSDL3Original.dll"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:NimbyRailsProxy>" "${CMAKE_BINARY_DIR}/proxy-test/SDL3.dll"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:NimbyRailsFranceSDK>" "${CMAKE_BINARY_DIR}/proxy-test/NimbyRailsFranceSDK.dll")
        add_test(NAME proxy_forwarding COMMAND nimby_proxy_tests "${CMAKE_BINARY_DIR}/proxy-test/SDL3.dll")
    endif()
endif()

if(BUILD_TESTING)
    add_library(nimby_native_library_fixture SHARED tests/native_library_fixture.cpp)
    add_executable(nimby_native_library_tests tests/native_library.cpp)
    target_include_directories(nimby_native_library_tests PRIVATE include)
    add_test(NAME native_library COMMAND nimby_native_library_tests $<TARGET_FILE:nimby_native_library_fixture>)
endif()

if(BUILD_TESTING)
    target_include_directories(nimby_native_library_fixture PRIVATE include)
    target_include_directories(nimby_signal_settings_file_tests PRIVATE tests/windows)
endif()

if(BUILD_TESTING)
    add_executable(nimby_texture_runtime_tests tests/texture_runtime.cpp)
    target_include_directories(nimby_texture_runtime_tests PRIVATE include)
    target_link_libraries(nimby_texture_runtime_tests PRIVATE nimby_build)
    add_test(NAME texture_runtime COMMAND nimby_texture_runtime_tests)
endif()

if(BUILD_TESTING)
    foreach(contract calendar_update physical_view)
        add_executable(nimby_${contract}_tests tests/${contract}.cpp)
        target_include_directories(nimby_${contract}_tests PRIVATE include)
        target_link_libraries(nimby_${contract}_tests PRIVATE nimby_build)
        add_test(NAME ${contract} COMMAND nimby_${contract}_tests)
    endforeach()
    add_executable(nimby_resource_tests tests/windows/resources.cpp)
    target_link_libraries(nimby_resource_tests PRIVATE NimbyRailsFranceSDK nimby_build)
    add_test(NAME windows_resource_lifetime COMMAND nimby_resource_tests)
    add_executable(nimby_texture_dispatch_tests tests/windows/texture_dispatch.cpp)
    target_include_directories(nimby_texture_dispatch_tests PRIVATE include)
    target_link_libraries(nimby_texture_dispatch_tests PRIVATE nimby_build)
    add_test(NAME windows_texture_dispatch COMMAND nimby_texture_dispatch_tests)
endif()

if(BUILD_TESTING)
    add_executable(nimby_game_language_tests tests/windows/game_language.cpp)
    target_include_directories(nimby_game_language_tests PRIVATE include)
    target_link_libraries(nimby_game_language_tests PRIVATE nimby_build)
    add_test(NAME windows_game_language COMMAND nimby_game_language_tests)
endif()
