"""Generate private ABI readers, never public pointer-based API. Run from any directory."""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = '\n'.join((root / 'include/nimby/detail' / name).read_text(encoding='utf-8') for name in ['sdk.h', 'observation.h'])
source = re.sub(r'//[^\n]*', '', source)
source = re.sub(r'union\s*\{[^}]+\};', 'uint32_t exception_count;', source)
types = {'uint64_t': (8, 'Long', 'getLong'), 'int64_t': (8, 'Long', 'getLong'),
         'uint32_t': (4, 'Int', 'getInt'), 'int32_t': (4, 'Int', 'getInt'),
         'double': (8, 'Double', 'getDouble'), 'char': (1, 'Byte', 'getByte'), 'uint8_t': (1, 'Byte', 'getByte')}
output = ['// Generated by tools/generate-kotlin-observation.py. Private ABI v2, pack(8).',
          'package fr.nimby.sdk.internal', 'import com.sun.jna.Pointer',
          'internal fun Pointer.utf8(offset: Long, size: Int): String {',
          '    val bytes = getByteArray(offset, size)',
          '    val end = bytes.indexOf(0).let { if (it < 0) size else it }',
          '    return bytes.copyOf(end).toString(Charsets.UTF_8)', '}']
for name, body in re.findall(r'typedef struct (Nimby\w+)\s*\{([^}]+)\}\s*\w+;', source):
    offset, align = 0, 1
    properties = []
    for field_type, names in re.findall(r'(uint64_t|int64_t|uint32_t|int32_t|double|char|uint8_t)\s+([^;]+);', body):
        width, kotlin, getter = types[field_type]
        for field in names.split(','):
            match = re.fullmatch(r'\s*(\w+)(?:\[(\d+)\])?\s*', field)
            if not match:
                raise ValueError(field)
            raw_name, count = match.groups()
            offset = (offset + width - 1) // width * width
            align = max(align, width)
            camel = re.sub(r'_([a-z])', lambda m: m[1].upper(), raw_name)
            if not raw_name.startswith('reserved'):
                if count and field_type == 'char':
                    properties.append(f'    val {camel}: String get() = p.utf8({offset}L, {count})')
                elif not count:
                    properties.append(f'    val {camel}: {kotlin} get() = p.{getter}({offset}L)')
            offset += width * (int(count) if count else 1)
    size = (offset + align - 1) // align * align
    output += [f'internal class {name}(private val p: Pointer) {{', f'    companion object {{ const val SIZE = {size} }}', *properties, '}']
target = root / 'kotlin-client/src/main/kotlin/fr/nimby/sdk/internal/NativeRecords.kt'
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text('\n'.join(output) + '\n', encoding='utf-8')
