# Linux host diagnostics and portable engine contracts. Game-specific hooks are
# deliberately not enabled until the Linux binary profile has been validated.
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8 OR NOT CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
    message(FATAL_ERROR "The current Linux research target requires x86-64")
endif()
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
include(CTest)
find_package(OpenSSL REQUIRED COMPONENTS Crypto)
find_package(Threads REQUIRED)
add_library(nimby_linux_process STATIC src/platform/linux/process.cpp src/platform/linux/memory_broker.cpp)
target_include_directories(nimby_linux_process PUBLIC include)
target_link_libraries(nimby_linux_process PUBLIC OpenSSL::Crypto Threads::Threads)
target_compile_options(nimby_linux_process PRIVATE -Wall -Wextra -Wpedantic)
set_target_properties(nimby_linux_process PROPERTIES POSITION_INDEPENDENT_CODE ON)
add_library(NimbyRailsFranceSDK SHARED src/main.cpp src/runtime/observation.cpp src/platform/linux/bootstrap.cpp
    src/runtime/runtime.cpp src/platform/linux/binary_identity.cpp
    src/engine/live_state.cpp src/engine/network.cpp src/engine/driving.cpp
    src/engine/track_usage.cpp src/engine/signal_textures.cpp)
target_compile_definitions(NimbyRailsFranceSDK PRIVATE NIMBY_SDK_BUILD)
target_include_directories(NimbyRailsFranceSDK PUBLIC include)
target_link_libraries(NimbyRailsFranceSDK PRIVATE nimby_linux_process ${CMAKE_DL_LIBS})
target_link_options(NimbyRailsFranceSDK PRIVATE -Wl,-z,defs)
set_target_properties(NimbyRailsFranceSDK PROPERTIES PREFIX "")
add_executable(nimby_linux_inspect tools/linux-inspect.cpp src/engine/live_state.cpp src/engine/network.cpp
    src/engine/track_usage.cpp src/engine/signal_textures.cpp)
target_link_libraries(nimby_linux_inspect PRIVATE nimby_linux_process)
install(TARGETS nimby_linux_inspect RUNTIME DESTINATION bin)
option(NIMBY_BUILD_LINUX_COMPAT "Build the optional game directory-read compatibility helper" OFF)
if(NIMBY_BUILD_LINUX_COMPAT)
    add_library(nimby_directory_read_guard SHARED tools/linux/directory-read-guard.c)
    target_link_libraries(nimby_directory_read_guard PRIVATE ${CMAKE_DL_LIBS})
    target_compile_options(nimby_directory_read_guard PRIVATE -Wall -Wextra)
    if(BUILD_TESTING)
        add_executable(nimby_directory_read_guard_tests tools/linux/directory-read-guard-test.c)
        target_compile_options(nimby_directory_read_guard_tests PRIVATE -UNDEBUG)
        add_test(NAME directory_read_guard COMMAND ${CMAKE_COMMAND} -E env
            "LD_PRELOAD=$<TARGET_FILE:nimby_directory_read_guard>"
            $<TARGET_FILE:nimby_directory_read_guard_tests>)
    endif()
endif()
# Compile the shared mod adapter independently while Linux game hooks are being
# qualified. Object compilation is not a distributable or a working game SDK.
add_library(nimby_linux_mod_adapter OBJECT src/mod/entry.cpp kotlin/native/adapter.cpp)
target_include_directories(nimby_linux_mod_adapter PRIVATE include)
target_compile_definitions(nimby_linux_mod_adapter PRIVATE NIMBY_KOTLIN_LIBRARY="ModKotlin.so")
set_target_properties(nimby_linux_mod_adapter PROPERTIES POSITION_INDEPENDENT_CODE ON)
if(BUILD_TESTING)
    add_library(nimby_linux_mod_fixture SHARED tests/linux_mod_fixture.cpp)
    add_executable(nimby_linux_mods_tests tests/linux_mods.cpp src/loader/mods.cpp)
    target_include_directories(nimby_linux_mods_tests PRIVATE include)
    target_compile_options(nimby_linux_mods_tests PRIVATE -Wall -Wextra -Wpedantic -UNDEBUG)
    target_link_libraries(nimby_linux_mods_tests PRIVATE ${CMAKE_DL_LIBS})
    add_test(NAME linux_mods COMMAND nimby_linux_mods_tests $<TARGET_FILE:nimby_linux_mod_fixture> $<TARGET_FILE:nimby_native_library_fixture>)
    add_library(nimby_native_library_fixture SHARED tests/native_library_fixture.cpp)
    add_executable(nimby_native_library_tests tests/native_library.cpp)
    target_include_directories(nimby_native_library_tests PRIVATE include)
    target_compile_options(nimby_native_library_tests PRIVATE -UNDEBUG)
    target_link_libraries(nimby_native_library_tests PRIVATE ${CMAKE_DL_LIBS})
    add_test(NAME native_library COMMAND nimby_native_library_tests $<TARGET_FILE:nimby_native_library_fixture>)
    function(nimby_portable_test name)
        add_executable(nimby_${name}_tests tests/${name}.cpp ${ARGN})
        target_include_directories(nimby_${name}_tests PRIVATE include)
        target_compile_options(nimby_${name}_tests PRIVATE -Wall -Wextra -Wpedantic -UNDEBUG)
        add_test(NAME ${name} COMMAND nimby_${name}_tests)
        set_tests_properties(${name} PROPERTIES TIMEOUT 30)
    endfunction()
    nimby_portable_test(linux_process)
    target_link_libraries(nimby_linux_process_tests PRIVATE nimby_linux_process)
    nimby_portable_test(linux_memory_broker)
    target_link_libraries(nimby_linux_memory_broker_tests PRIVATE nimby_linux_process)
    nimby_portable_test(linux_runtime)
    target_link_libraries(nimby_linux_runtime_tests PRIVATE NimbyRailsFranceSDK)
    nimby_portable_test(live_state src/engine/live_state.cpp)
    nimby_portable_test(native_string)
    nimby_portable_test(network src/engine/network.cpp src/engine/live_state.cpp)
    nimby_portable_test(track_usage src/engine/track_usage.cpp src/engine/live_state.cpp)
    nimby_portable_test(signal_textures src/engine/signal_textures.cpp src/engine/live_state.cpp)
    nimby_portable_test(versioning src/engine/live_state.cpp)
    nimby_portable_test(driving src/engine/driving.cpp src/engine/live_state.cpp)
    nimby_portable_test(blocks)
    nimby_portable_test(block_topology)
    nimby_portable_test(signal_topology)
    nimby_portable_test(signal_extensions)
    nimby_portable_test(signal_settings_store)
    nimby_portable_test(signal_settings_catalog)
    nimby_portable_test(signal_settings_file)
    nimby_portable_test(signal_ui)
    nimby_portable_test(signal_ui_endpoint)
    nimby_portable_test(signalling_runtime tests/portable_texture_doubles.cpp)
    nimby_portable_test(automatic_driving)
endif()
